### ISSUE TITLE
Error when loading checkpoint model

### ISSUE THREAD

**Issue by songyuzhou324** [okuchaiev/f-lm#4]
After training a G-LSTM, I got error when evaluating it:

W tensorflow/core/framework/op_kernel.cc:993] Not found: Key model/lstm_0/lstm_cell/biases not found in checkpoint

This error occurs when restoring the ckpt model.

How can I solve this issue?

**Comment by okuchaiev** [comment]
Looks like you are trying to load a glstm model into lstm-based graph
